# Generated by Axiom CLI — do not delete.
# Ensures pytest can resolve "from nodes.<module> import <func>" imports
# whether tests are run from the package root or inside the Docker build.
import sys, os as _os
sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))
